# Generated by Django 4.1 on 2022-08-24 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeptMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_id",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                        verbose_name="ID",
                    ),
                ),
                ("dept", models.CharField(max_length=20, verbose_name="部署名")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="備考"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListOfPurchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=50, verbose_name="商品名")),
                ("deploy_id", models.CharField(max_length=8, verbose_name="部署ID")),
                ("store_id", models.CharField(max_length=8, verbose_name="購入先ID")),
                (
                    "user_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="担当者名"
                    ),
                ),
                ("unit_prise", models.IntegerField(verbose_name="単価")),
                ("quantity", models.IntegerField(verbose_name="数量")),
                ("total_due", models.IntegerField(verbose_name="金額")),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "insert_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "update_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaserMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_id",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=20, verbose_name="購入先")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="備考"
                    ),
                ),
            ],
        ),
    ]
