# Generated by Django 4.0.6 on 2022-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpurchases',
            name='deploy_id',
            field=models.CharField(max_length=100, verbose_name='部署ID'),
        ),
        migrations.AlterField(
            model_name='listofpurchases',
            name='store_id',
            field=models.CharField(max_length=100, verbose_name='購入先ID'),
        ),
    ]
