# Generated by Django 4.0.6 on 2022-08-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=10, verbose_name='')),
                ('dept', models.CharField(max_length=20, verbose_name='部署名')),
                ('note', models.CharField(max_length=30, verbose_name='備考')),
            ],
        ),
    ]
