# Generated by Django 4.1 on 2022-08-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="listofpurchases", name="order_plan",),
    ]
