# Generated by Django 4.0.6 on 2022-08-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptmaster',
            name='dept_id',
            field=models.CharField(max_length=10, verbose_name='ID'),
        ),
    ]
