# Generated by Django 4.0.6 on 2022-09-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_listofpurchases_order_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofpurchases',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='listofpurchases',
            old_name='store_id',
            new_name='store',
        ),
    ]
