# Generated by Django 2.1.15 on 2022-09-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_rename_dept_id_listofpurchases_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptmaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listofpurchases',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchasermaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
