# Generated by Django 4.0.7 on 2022-09-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_alter_deptmaster_id_alter_listofpurchases_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptmaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='listofpurchases',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purchasermaster',
            options={'managed': False},
        ),
    ]
