# Generated by Django 4.0.7 on 2022-09-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_alter_deptmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listofpurchases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchasermaster',
            options={},
        ),
    ]
