# Generated by Django 4.0.7 on 2022-09-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_alter_deptmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptmaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listofpurchases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasermaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
